source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0

target 'Example', :exclusive => true do
  # pod 'AsyncDisplayKit', '~> 1.0.1'
  pod "AsyncDisplayKit", :path => "../AsyncDisplayKit"
  pod 'Reveal-iOS-SDK'

  pod 'KRLCollectionViewGridLayout', '~> 0.1.1'
end