source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0


target 'mxAsTubeiPad', :exclusive => true do

  pod 'AsyncDisplayKit', :git => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/AsyncDisplayKit', :commit => '5cb261b'

  pod 'Reveal-iOS-SDK'
  pod 'pop', '~> 1.0.7'

  #pod 'NSLogger', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/NSLogger'

  pod 'Regexer', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/Regexer'

  #pod 'MagicalRecord', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/MagicalRecord'

  # ________________open projects___________________
  pod "GGTabBar", :path => "../dependencies/lib/GGTabBar"
  pod "YKMediaPlayerKit", :path => "../dependencies/lib/YKMediaPlayerKit"
  #pod "MPMoviePlayerController-Subtitles", :path => "../dependencies/lib/MPMoviePlayerController-Subtitles"
  pod 'SWRevealViewController', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/SWRevealViewController'

  pod 'AFNetworking', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/AFNetworking'
  pod "KRLCollectionViewGridLayout", :path => "../dependencies/lib/KRLCollectionViewGridLayout"

  pod 'ISMemoryCache', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/ISMemoryCache'

  pod 'SDWebImage', '~> 100.7.1'
  #pod 'SDWebImage', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/SDWebImage'


  pod 'EGOCache', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/EGOCache'

  pod "YouTubeAPI3-Objective-C-wrapper", :path => "../dependencies/lib/YouTubeAPI3-Objective-C-wrapper"

  pod "Google-API-Client-local", :path => "/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/google-api-client/Google-API-Client-local"
  pod "gtm-http-fetcher-local", :path => "/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/google-api-client/gtm-http-fetcher-local"
  pod "gtm-oauth2-local", :path => "/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/google-api-client/gtm-oauth2-local"

  pod 'ASImageResize', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/ASImageResize'

  pod 'XMLDictionary', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/XMLDictionary'



  # ________________collect common library___________________
  pod "IOS_Collection_Code", :path => "../dependencies/collect/IOS_Collection_Code"

  # ________________Project layers___________________
  pod "Business-Logic-Layer", :path => "../dependencies/layers/Business-Logic-Layer"
  pod "google-api-services-youtube", :path => "../dependencies/layers/google-api-services-youtube"

  # ________________Projects for iPad___________________
  # ________________module Projects___________________
  pod "VideoWatchDetailViewControlleriPad", :path => "../dependencies/ipad/VideoWatchDetailViewControlleriPad"
  pod "Youtube_ChannelPage_Controller", :path => "../dependencies/ipad/Youtube_ChannelPage_Controller"
  pod "youtube_slide_menu", :path => "../dependencies/ipad/youtube_slide_menu"
  pod "YoutubeCollectionView", :path => "../dependencies/ipad/YoutubeCollectionView"

end

target 'mxAsTubeiPadTests', :exclusive => true do

  # pod 'OCMockito', '~> 1.0'

  #pod 'OCHamcrest', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/OCHamcrest'
  #pod 'OCMockito', :path => '/Volumes/Home/Developing/wanghaogithub720/cocoapods/Cocoapods_Libraries/OCMockito'


end
