source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0


target 'mxAsTubeiPad', :exclusive => true do

  # ________________common tools library___________________
  pod 'ASImageResize'
  pod 'XMLDictionary'
  pod 'Regexer'
  pod 'Bolts'
  pod 'Reveal-iOS-SDK'
  pod 'pop'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'SWRevealViewController'
  pod 'ISMemoryCache'
  pod 'EGOCache'

  pod 'AsyncDisplayKit', :git => '/Volumes/Home/wanghaogithub720/cocoapods/Cocoapods_Libraries/AsyncDisplayKit', :commit => '5cb261b'

  # ________________open projects___________________
  pod "GGTabBar", :path => "../dependencies/lib/GGTabBar"
  pod "YKMediaPlayerKit", :path => "../dependencies/lib/YKMediaPlayerKit"
  pod "MPMoviePlayerController-Subtitles", :path => "../dependencies/lib/MPMoviePlayerController-Subtitles"
  pod "KRLCollectionViewGridLayout", :path => "../dependencies/lib/KRLCollectionViewGridLayout"

  # ________________Google-API-Client___________________
  pod "YouTubeAPI3-Objective-C-wrapper", :path => "../dependencies/lib/YouTubeAPI3-Objective-C-wrapper"
  pod 'Google-API-Client'


  # ________________collect common library___________________
  pod "IOS_Collection_Code", :path => "../dependencies/collect/IOS_Collection_Code"

  # ________________Project layers___________________
  pod "Business-Logic-Layer", :path => "../dependencies/layers/Business-Logic-Layer"
  pod "google-api-services-youtube", :path => "../dependencies/layers/google-api-services-youtube"

  # ________________Projects for iPad___________________
  # ________________module Projects___________________
  pod "VideoWatchDetailViewControlleriPad", :path => "../dependencies/ipad/VideoWatchDetailViewControlleriPad"
  pod "Youtube_ChannelPage_Controller", :path => "../dependencies/ipad/Youtube_ChannelPage_Controller"
  pod "youtube_slide_menu", :path => "../dependencies/ipad/youtube_slide_menu"
  pod "YoutubeCollectionView", :path => "../dependencies/ipad/YoutubeCollectionView"

end

target 'mxAsTubeiPadTests', :exclusive => true do
  # pod 'OCMockito', '~> 1.0'

end
